framework:
    messenger:
        failure_transport: failed

        transports:
#            async:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                # Настройка повторов отличная, добавим только начальную задержку
#                retry_strategy:
#                    max_retries: 3
#                    delay: 1000          # Первая попытка через 1 секунду
#                    multiplier: 2        # Каждая следующая задержка удваивается (1с -> 2с -> 4с)
#
            async:
                dsn: '%env(RABBITMQ_URL)%'
                options:
                    exchange:
                        name: 'async_exchange'
                        type: 'direct'
                    queues:
                        messages:
                            arguments:
                                x-max-priority: 10
            failed: 'doctrine://default?queue_name=failed'
        default_bus: command.bus

        buses:
            event.bus: ~

            command.bus:
                middleware:
                    - doctrine_transaction

            query.bus:
                middleware: []

        routing:
            'App\Contract\AsyncMessageInterface': async
