services:
    nginx:
        image: nginx:1.29.8
        ports:
            - "8002:80"
        volumes:
            - .:/var/www/test3
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
        restart: always
        depends_on:
            php:
                condition: service_started
        networks:
            - app

    mysql:
        image: mysql:9.7.0
        ports:
            - "8004:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task_manager
            MYSQL_USER: task_manager
            MYSQL_PASSWORD: task_manager
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
            timeout: 3s
            retries: 15
            start_period: 1s
        networks:
            - data

    redis:
        image: redis:8.6-alpine3.23
        ports:
            - "8005:6379"
        restart: always
        volumes:
            - ./docker/redis/data:/data
        command: redis-server --appendonly yes
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            timeout: 10s
            retries: 5
            start_period: 5s
        networks:
            - data

    mongodb:
        image: mongo:latest
        ports:
            - "8006:27017"
        volumes:
            - ./docker/mongodb/data:/data/db
        restart: always
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            timeout: 10s
            retries: 5
            start_period: 10s
        networks:
            - data

    mercure:
        image: dunglas/mercure
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: 'l+GvN1/vT4ik8oxZL848Jm7ehk1zN64oEH0yr8AWBpA='
            MERCURE_SUBSCRIBER_JWT_KEY: 'l+GvN1/vT4ik8oxZL848Jm7ehk1zN64oEH0yr8AWBpA='
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins "*"
                publish_origins "http://localhost:8002"
                anonymous 1
                subscriptions 1
        ports:
            - "8008:80"
        restart: always
        networks:
            - app

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: dev
        volumes:
            - ~/.gitconfig:/home/appuser/.gitconfig:ro
            - .:/var/www/test3
        restart: always
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
            mongodb:
                condition: service_healthy
        networks:
            - app
            - data

    rabbitmq:
        image: rabbitmq:4.3.2-management-alpine
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - "5672:5672"    # основной порт для подключения
            - "15672:15672"  # веб-интерфейс (менеджмент)
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_VHOST: /
        volumes:
            - ./docker/rabbitmq/data:/var/lib/rabbitmq
            - ./docker/rabbitmq/logs:/var/log/rabbitmq
        restart: unless-stopped
        networks:
            - app
            - data

networks:
    app:
        driver: bridge
    data:
        driver: bridge
