[program:messenger]
command=php /var/www/test3/bin/console messenger:consume async -vv --time-limit=3600 --memory-limit=512M
directory=/var/www/test3
user=appuser
autostart=true
autorestart=true
startretries=3
numprocs=2
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/supervisor/messenger.out.log
stderr_logfile=/var/log/supervisor/messenger.err.log
